// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P1_AP1_JoseOrtega.DAL;

#nullable disable

namespace P1_AP1_JoseOrtega.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251009190912_Septima")]
    partial class Septima
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("EntradasHuacalesTiposHuacales", b =>
                {
                    b.Property<int>("TipoHuacaleTipoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoHuacaleTipoId", "TipoId");

                    b.HasIndex("TipoId");

                    b.ToTable("EntradasHuacalesTiposHuacales");
                });

            modelBuilder.Entity("P1_AP1_JoseOrtega.Models.EntradasHuacales", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("IdEntrada");

                    b.ToTable("EntradasHuacales");
                });

            modelBuilder.Entity("P1_AP1_JoseOrtega.Models.EntradasHuacalesDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("IdEntrada");

                    b.ToTable("entradasHuacalesDetalles");
                });

            modelBuilder.Entity("P1_AP1_JoseOrtega.Models.TiposHuacales", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoId");

                    b.ToTable("TiposHuacales");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripcion = "Huacal verde pequeño",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 2,
                            Descripcion = "Huacal rojo pequeño",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 3,
                            Descripcion = "Huacal verde mediano",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 4,
                            Descripcion = "Huacal rojo mediano",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 5,
                            Descripcion = "Huacal verde Grande",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 6,
                            Descripcion = "Huacal rojo grande",
                            Existencia = 0
                        });
                });

            modelBuilder.Entity("EntradasHuacalesTiposHuacales", b =>
                {
                    b.HasOne("P1_AP1_JoseOrtega.Models.TiposHuacales", null)
                        .WithMany()
                        .HasForeignKey("TipoHuacaleTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P1_AP1_JoseOrtega.Models.EntradasHuacales", null)
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("P1_AP1_JoseOrtega.Models.EntradasHuacalesDetalle", b =>
                {
                    b.HasOne("P1_AP1_JoseOrtega.Models.EntradasHuacales", "EntradaHuacale")
                        .WithMany("EntradaHuacaleDetalle")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradaHuacale");
                });

            modelBuilder.Entity("P1_AP1_JoseOrtega.Models.EntradasHuacales", b =>
                {
                    b.Navigation("EntradaHuacaleDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
