// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P1_AP1_JoseOrtega.DAL;

#nullable disable

namespace P1_AP1_JoseOrtega.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251009023606_Cuarta")]
    partial class Cuarta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("P1_AP1_JoseOrtega.Models.EntradasHuacales", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("IdEntrada");

                    b.ToTable("EntradasHuacales");
                });

            modelBuilder.Entity("P1_AP1_JoseOrtega.Models.EntradasHuacalesDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Precio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("IdEntrada");

                    b.ToTable("EntradasHuacalesDetalle");
                });

            modelBuilder.Entity("P1_AP1_JoseOrtega.Models.EntradasHuacalesDetalle", b =>
                {
                    b.HasOne("P1_AP1_JoseOrtega.Models.EntradasHuacales", "EntradaHuacale")
                        .WithMany("EntradaHuacaleDetalle")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradaHuacale");
                });

            modelBuilder.Entity("P1_AP1_JoseOrtega.Models.EntradasHuacales", b =>
                {
                    b.Navigation("EntradaHuacaleDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
